### ISSUE TITLE
String matching

### ISSUE THREAD

**Issue by stellargo** [stellargo/meseek#13]
for our own db we need to be able to match strings to some certain percentage

**Comment by stellargo** [comment]
Write a function that gives a percentage of match between two strings.

**Comment by abhimanyuchaudhary** [comment]
assign pls sir

**Comment by abhimanyuchaudhary** [comment]
also we have 4 algorithms
Hamming distance
Levenshtein distance
Damerau–Levenshtein distance
Jaro–Winkler distance
Which one do you want

**Comment by stellargo** [comment]
I think Levenshtein, but you can read about all including wagner fischer, and see where our need gets the result in least time :)

**Comment by stellargo** [comment]
Apparently gihub will allow me to assign it to you only if you had created the issue :( Go on submit a PR, forget the assigning stuff :)

**Comment by abhimanyuchaudhary** [comment]
thanks sir you are so great
